# Generated by Django 5.1.4 on 2025-01-02 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('attack_id', models.CharField(max_length=512)),
                ('name', models.CharField(max_length=200)),
                ('name_display', models.CharField(max_length=200, null=True)),
                ('cost', models.JSONField(null=True, verbose_name='attack_cost')),
                ('damage', models.IntegerField(null=True)),
                ('is_no_damage', models.BooleanField(null=True)),
                ('damage_symbol', models.CharField(max_length=8, null=True)),
                ('effect', models.JSONField(null=True, verbose_name='attack_effect')),
                ('attack_description', models.CharField(max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pokedex_number', models.SmallIntegerField(null=True)),
                ('name', models.CharField(max_length=128)),
                ('name_display', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=True)),
                ('attack_ids', models.JSONField(null=True, verbose_name='card_attack_ids')),
                ('card_id', models.CharField(max_length=64, null=True)),
                ('card_pokemon_id', models.CharField(max_length=64, null=True)),
                ('card_trainer_id', models.CharField(max_length=64, null=True)),
                ('card_trainer_type', models.CharField(choices=[('F', 'Fossil'), ('I', 'Item'), ('S', 'Supporter')], max_length=1, null=True)),
                ('card_type', models.CharField(choices=[('P', 'Pokemon'), ('T', 'Trainer')], max_length=128)),
                ('character_id', models.CharField(max_length=128, null=True)),
                ('collection_number', models.SmallIntegerField(null=True)),
                ('description', models.CharField(max_length=2048, null=True)),
                ('dust_cost', models.IntegerField(null=True)),
                ('effect', models.JSONField(null=True, verbose_name='card_effect')),
                ('expansion_id', models.CharField(max_length=64, null=True)),
                ('flavor_text', models.CharField(max_length=2048, null=True)),
                ('is_promo', models.BooleanField(null=True)),
                ('is_serial', models.BooleanField(null=True)),
                ('promotion_name', models.CharField(max_length=512, null=True)),
                ('rules_description', models.CharField(max_length=2048, null=True)),
                ('series_id', models.CharField(max_length=8, null=True)),
                ('variants', models.JSONField(null=True, verbose_name='card_variants')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('name_display', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expansion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('expansion_id', models.CharField(max_length=64, null=True)),
                ('name', models.CharField(max_length=512, null=True)),
                ('name_display', models.CharField(max_length=512, null=True)),
                ('card_count', models.IntegerField(null=True)),
                ('is_promo', models.BooleanField()),
                ('sort_number', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Illustrator',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rarity_id', models.CharField(choices=[('C', 'Common'), ('U', 'Uncommon'), ('R', 'Rare'), ('RR', 'Double Rare'), ('AR', 'Art Rare'), ('SR', 'Super Rare'), ('IM', 'Immersive'), ('UR', 'Ultra Rare'), ('SAR', 'Special Art Rare')], max_length=8)),
                ('name', models.CharField(max_length=64)),
                ('name_display', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cards.card')),
                ('trainer_id', models.CharField(max_length=512)),
                ('trainer_type', models.CharField(choices=[('F', 'Fossil'), ('I', 'Item'), ('S', 'Supporter')], max_length=1, null=True)),
                ('trainer_type_label', models.CharField(max_length=32, null=True)),
            ],
            bases=('cards.card', models.Model),
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pack_id', models.CharField(max_length=64, null=True)),
                ('name', models.CharField(max_length=512, null=True)),
                ('name_display', models.CharField(max_length=512, null=True)),
                ('sort_number', models.SmallIntegerField(null=True)),
                ('expansion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='cards.expansion')),
            ],
        ),
        migrations.CreateModel(
            name='CardPack',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cards.card')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cards.pack')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='rarity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='cards.rarity'),
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cards.card')),
                ('pokemon_id', models.CharField(max_length=512)),
                ('stage_number', models.SmallIntegerField(null=True)),
                ('stage_name', models.CharField(choices=[('Basic', 'Basic'), ('Stage 1', 'Stage 1'), ('Stage 2', 'Stage 2')], max_length=16, null=True)),
                ('hp', models.SmallIntegerField(null=True)),
                ('is_ex', models.BooleanField(null=True)),
                ('previous_evolution', models.CharField(max_length=512, null=True)),
                ('retreat_cost_number', models.SmallIntegerField(null=True)),
                ('retreat_cost_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pokemon_retreat_cost_type', to='cards.energytype')),
                ('weakness_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pokemon_weakness_type', to='cards.energytype')),
            ],
            bases=('cards.card', models.Model),
        ),
        migrations.CreateModel(
            name='CardAttack',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('attack', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='card_attacks_attack', to='cards.attack')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='card_attacks_card', to='cards.card')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('card', 'attack'), name='unique_card_attack')],
            },
        ),
        migrations.CreateModel(
            name='CardIllustrator',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cards.card')),
                ('illustrator', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cards.illustrator')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('card', 'illustrator'), name='unique_card_illustrator')],
            },
        ),
    ]
