# Generated by Django 5.1.4 on 2024-12-18 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('name_display', models.CharField(max_length=200, null=True)),
                ('cost', models.JSONField(null=True, verbose_name='attack_cost')),
                ('damage', models.IntegerField(null=True)),
                ('effect', models.JSONField(null=True, verbose_name='attack_effect')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('name_display', models.CharField(max_length=200, null=True)),
                ('effect', models.JSONField(null=True, verbose_name='card_effect')),
                ('illustrator', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('name_display', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnergyType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('name_display', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.SmallIntegerField()),
                ('name', models.CharField(max_length=200, unique=True)),
                ('name_display', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cards.card')),
                ('ex', models.BooleanField(null=True)),
                ('stage', models.SmallIntegerField(null=True)),
                ('hp', models.IntegerField(null=True)),
                ('weakness_amount', models.IntegerField(null=True)),
                ('retreat_cost', models.SmallIntegerField(null=True)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.energytype')),
                ('weakness_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokemon_weakness_type', to='cards.energytype')),
            ],
            bases=('cards.card', models.Model),
        ),
        migrations.AddField(
            model_name='card',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.cardcategory'),
        ),
        migrations.AddField(
            model_name='card',
            name='rarity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_rarity', to='cards.rarity'),
        ),
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=8)),
                ('set_number', models.CharField(max_length=200, unique=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cards.card')),
                ('dex', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cards.set')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='card_set_set', to='cards.set')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('card', 'set', 'dex'), name='unique_card_set_dex')],
            },
        ),
        migrations.CreateModel(
            name='PokemonAttack',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('attack', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cards.attack')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cards.pokemon')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('pokemon', 'attack'), name='unique_pokemon_attack')],
            },
        ),
    ]
