# Generated by Django 5.1.4 on 2024-12-20 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('card_id', models.CharField(max_length=200, null=True)),
                ('card_type', models.CharField(choices=[('P', 'Pokemon'), ('T', 'Trainer')], max_length=128)),
                ('character_id', models.CharField(max_length=200, null=True)),
                ('collection_number', models.SmallIntegerField(null=True)),
                ('description', models.CharField(max_length=2048, null=True)),
                ('dust_cost', models.IntegerField(null=True)),
                ('effect', models.JSONField(null=True, verbose_name='card_effect')),
                ('expansion_id', models.CharField(max_length=64, null=True)),
                ('flavor_text', models.CharField(max_length=2048, null=True)),
                ('is_promo', models.BooleanField(null=True)),
                ('is_serial', models.BooleanField(null=True)),
                ('name', models.CharField(max_length=200)),
                ('name_display', models.CharField(max_length=200)),
                ('pokedex_number', models.SmallIntegerField(null=True)),
                ('promotion_name', models.CharField(max_length=512, null=True)),
                ('rarity', models.CharField(choices=[('C', 'Common'), ('U', 'Uncommon'), ('R', 'Rare'), ('RR', 'Double Rare'), ('AR', 'Art Rare'), ('SR', 'Super Rare'), ('IM', 'Immersive'), ('UR', 'Ultra Rare'), ('SAR', 'Special Art Rare')], max_length=32, null=True)),
                ('rules_description', models.CharField(max_length=2048, null=True)),
                ('trainer_type', models.CharField(choices=[('I', 'Item'), ('S', 'Supporter')], max_length=1, null=True)),
                ('series_id', models.CharField(max_length=8, null=True)),
                ('variants', models.JSONField(null=True, verbose_name='card_variants')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('name_display', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expansion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('expansion_id', models.CharField(max_length=64, null=True)),
                ('name', models.CharField(max_length=512, null=True)),
                ('name_display', models.CharField(max_length=512, null=True)),
                ('card_count', models.IntegerField(null=True)),
                ('is_promo', models.BooleanField()),
                ('sort_order_priority', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Illustrator',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('name_display', models.CharField(max_length=200, null=True)),
                ('cost', models.JSONField(null=True, verbose_name='attack_cost')),
                ('damage', models.IntegerField(null=True)),
                ('effect', models.JSONField(null=True, verbose_name='attack_effect')),
                ('effect_description', models.CharField(max_length=512, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'damage', 'cost'), name='unique_name_damage_cost')],
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cards.card')),
            ],
            bases=('cards.card', models.Model),
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pack_id', models.CharField(max_length=64, null=True)),
                ('name', models.CharField(max_length=512, null=True)),
                ('name_display', models.CharField(max_length=512, null=True)),
                ('expansion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='cards.expansion')),
            ],
        ),
        migrations.CreateModel(
            name='CardPack',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cards.card')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cards.pack')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cards.card')),
                ('stage', models.CharField(choices=[('Basic', 'Basic'), ('Stage 1', 'Stage 1'), ('Stage 2', 'Stage 2')], max_length=16, null=True)),
                ('ex', models.BooleanField(null=True)),
                ('hp', models.IntegerField(null=True)),
                ('retreat_cost', models.SmallIntegerField(null=True)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.energytype')),
                ('weakness_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokemon_weakness_type', to='cards.energytype')),
            ],
            bases=('cards.card', models.Model),
        ),
        migrations.CreateModel(
            name='CardAttack',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('attack', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='card_attack_attacks', to='cards.attack')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='card_attack_cards', to='cards.card')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('card', 'attack'), name='unique_card_attack')],
            },
        ),
        migrations.CreateModel(
            name='CardIllustrator',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cards.card')),
                ('illustrator', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cards.illustrator')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('card', 'illustrator'), name='unique_card_illustrator')],
            },
        ),
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=8)),
                ('set_number', models.CharField(max_length=200)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cards.card')),
                ('dex', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='cards.set')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='card_set_set', to='cards.set')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('card', 'set', 'dex', 'number'), name='unique_card_set_dex_number')],
            },
        ),
    ]
