# Generated by Django 5.1.4 on 2025-01-07 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('in_matchmaking', models.BooleanField(default=True)),
                ('points', models.SmallIntegerField(default=0)),
                ('hand_card_ids', models.JSONField(null=True)),
                ('draw_pile', models.JSONField(null=True)),
                ('discard_pile', models.JSONField(default=list)),
                ('active_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_active_card', to='cards.card')),
                ('bench_1_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_bench_1_card', to='cards.card')),
                ('bench_2_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_bench_2_card', to='cards.card')),
                ('bench_3_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_bench_3_card', to='cards.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('battle_id', models.BigIntegerField(null=True)),
                ('active', models.BooleanField(default=False)),
                ('started', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('player_1_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battle_player_1', to='battle.player')),
                ('player_2_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battle_player_2', to='battle.player')),
                ('starting_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battle_starting_player', to='battle.player')),
                ('winning_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='battle.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerDeck',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('card_ids', models.JSONField(null=True)),
                ('card_1', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='player_deck_card_1', to='cards.card')),
                ('card_10', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='player_deck_card_10', to='cards.card')),
                ('card_11', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='player_deck_card_11', to='cards.card')),
                ('card_12', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='player_deck_card_12', to='cards.card')),
                ('card_13', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='player_deck_card_13', to='cards.card')),
                ('card_14', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='player_deck_card_14', to='cards.card')),
                ('card_15', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='player_deck_card_15', to='cards.card')),
                ('card_16', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='player_deck_card_16', to='cards.card')),
                ('card_17', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='player_deck_card_17', to='cards.card')),
                ('card_18', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='player_deck_card_18', to='cards.card')),
                ('card_19', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='player_deck_card_19', to='cards.card')),
                ('card_2', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='player_deck_card_2', to='cards.card')),
                ('card_20', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='player_deck_card_20', to='cards.card')),
                ('card_3', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='player_deck_card_3', to='cards.card')),
                ('card_4', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='player_deck_card_4', to='cards.card')),
                ('card_5', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='player_deck_card_5', to='cards.card')),
                ('card_6', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='player_deck_card_6', to='cards.card')),
                ('card_7', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='player_deck_card_7', to='cards.card')),
                ('card_8', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='player_deck_card_8', to='cards.card')),
                ('card_9', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='player_deck_card_9', to='cards.card')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.player')),
            ],
        ),
    ]
